In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
slice_of_array = arr[0:6]

In [28]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [29]:
slice_of_array[:] = 99

In [30]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [31]:
arr_copy = arr.copy()

In [32]:
arr_copy[:] = 100

In [33]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [34]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### 2D Array

In [35]:
arr_2d = np.array([[1,2,3],[4,5,6],[3,4,6]])

In [37]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 6]])

In [43]:
arr_2d[0,2]

3

In [44]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [45]:
arr_2d[:2,:1]

array([[1],
       [4]])

In [48]:
arr_2d[2:,1:]

array([[4, 6]])

In [49]:
arr = np.arange(0,11)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
bool_arr = arr > 6

In [53]:
bool_arr

array([False, False, False, False, False, False, False,  True,  True,
        True,  True])

In [54]:
arr[bool_arr]

array([ 7,  8,  9, 10])

In [55]:
arr[arr<5]

array([0, 1, 2, 3, 4])

In [56]:
arr_2d = np.arange(50).reshape(5,10)

In [58]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [60]:
arr_2d[1:3,2:6]

array([[12, 13, 14, 15],
       [22, 23, 24, 25]])